### PR TITLE
Implement extended open api

### PR DESCRIPTION
**Pull request by eugen0329**
Implement EXPERIMENTAL API:
```vim
call b:esearch.open({opener}, [{options}])
call b:esearch.preview()
call b:esearch.filename()
call b:esearch.line_in_file()
call b:esearch.is_filename()
call b:esearch.is_entry()
call b:esearch.jump2entry({direction}, {count})
call b:esearch.jump2filename({direction}, {count})
 " Checks if self == b:esearch. Relevant mostly for debouncer 
call b:esearch.is_current()
```

Expose events:
```vim
esearch#init_pre
esearch#out#win#init_pre
esearch#out#win#init_post
esearch#out#win#uninit_post
```

Usage examples:
```vim
" Open a split if cursor is hold for 500ms staying in the search window.
" Also ensures it's the only split opened
au User esearch#out#win#init_post
      \  let b:open = esearch#debounce#trailing(b:esearch.open, 500)
      \| au CursorMoved <buffer> call b:open.invoke('vnew', {'stay': 1, 'once': 1})
au User esearch#out#win#uninit_post
      \ call b:esearch.opened_once_manager.close()
```
```vim
" Open a preview window on hover after waiting for 1000ms
au User esearch#out#win#init_post
      \ | let b:preview = esearch#debounce#trailing(b:esearch.preview, 1000)
      \ | au CursorMoved <buffer> call b:preview.invoke()
```
```vim
" Map e key to open using a custom opener function.
" Also set 'eventignore' option to skip BufLeave per opening
call esearch#out#win#map('e', 
      \ {-> b:esearch.open(function('MyOpener'), {'let': {'&ei': 'BufLeave'}})

" Map z key to open using topleft modifier and set UTF-8 encoding.
call esearch#out#win#map('z',
      \ {-> b:esearch.open('vsplit', {'mods': 'topleft', 'cmdarg': '++enc=utf8'})})

" Map <C-u> and <C-d> to jump 10 entries up and down correspondingly
call esearch#out#win#map('<C-u>', {-> b:esearch.jump2entry('^', 10 * v:count1)})
call esearch#out#win#map('<C-d>', {-> b:esearch.jump2entry('v', 10 * v:count1)})

" Map <Space> to jump to the next filename ("--show more--"-like scrolling down)
call esearch#out#win#map('<Space>', {-> b:esearch.jump2filename('v', v:count1)})
```

### CODE REVIEW

**Comment by ipod825** [comment]
> " Open a preview window on hover after waiting for 1000ms
au User esearch#out#win#init_post
      \ | let b:preview = esearch#debounce#trailing(b:esearch.preview, 1000)
      \ | au CursorMoved <buffer> call b:preview.invoke()

This seems to modify the undo history of a file. If you move cursor over searching result, after opening the file, pressing `u` you won't see `Already at oldest change`.

**Comment by eugen0329** [comment]
Can't reproduce. Tried:
1. Open a file
2. Search a word from it
3. Put the cursror above and wait until it's opened
4. Try to undo both search win and within opened file and `Already at..` is printed

Can you provide you steps, please?

**Comment by ipod825** [comment]
> Can't reproduce. Tried:

vim config:
```vim
let g:vim_dir=fnamemodify($MYVIMRC, ":h")."/"
" Download vim-plug
call plug#begin(g:vim_dir . 'bundle')
Plug 'eugen0329/vim-esearch', {'branch': 'development'}
call plug#end()
au User esearch#out#win#init_post
  \  let b:open = esearch#debounce#trailing(b:esearch.open, 100)
  \| au CursorMoved <buffer> call b:open.invoke('vnew', {'stay': 1, 'once': 1})
```

The steps are exactly the same as yours. Not sure if it's vim version's problem:
```bash
$ nvim --version
NVIM v0.5.0-418-g87d892afa
```

**Comment by eugen0329** [comment]
Does it happen within a search window or within a file? The window always has the first undo block duplicate to allow easymotion to do a hack with locking undotree.

**Comment by ipod825** [comment]
>Does it happen within a search window or within a file? The window always has the first undo block duplicate to allow easymotion to do a hack with locking undotree.

Within the file. Pressing `u` in either the preview buffer in the search tabpage or the original buffer shows some undo steps.

**Comment by eugen0329** [comment]
Finally reproduced with split preview. Floating is still working fine, though.

**Comment by eugen0329** [comment]
Replied in https://github.com/eugen0329/vim-esearch/pull/107#issuecomment-602485854

**Pull request merged**
