### PR TITLE
Allow specifying context height

### PR DESCRIPTION
**Pull request by eugen0329**

### CODE REVIEW

**Comment by eugen0329** [comment]
@ipod825

I've added some drafts to output results context. Can be enabled by `let g:esearch.context = 2`. Could you check if this is what you expect, please?

**Comment by ipod825** [comment]
I don't know I asked for anything :) But anyway, what's this feature about? I don't understand it by viewing the commit.

**Comment by eugen0329** [comment]
It's originally described in https://github.com/eugen0329/vim-esearch/issues/23, but the author seems to not be active on github lately, so I decided to ping only you to get the feedback. And yeah, I forgot that you quoted a comment about previews there rather than about contexts, but nonetheless :)

In short, it adds an option to output N lines below and above a line with matches. Context line may or may not contain matches and serves only to better understand where the match is located. It's literally a frontend for `-C`, `-A` and `-B` options used by grep and others.

Another use case is to set `-A 3`  to search methods by name pattern and remove or modify their three-line bodies right from the search window or use `-B 3` to remove some decorators above python setter methods. (-A and -B aren't commited yet, but they're on the way)

**Comment by ipod825** [comment]
I don't see why we need this feature if we have preview window, which shows far more context.

**Comment by eugen0329** [comment]
The most useful thing it's applicable to is to make batch modifications like changing or removing of entire method bodies or code blocks. Not all search utils support multiline matching and even if you use the one that supports (like ag), its not really convenient to build multiline regexp to do this.

And it was also a feature request, so probably the original issue author will find it useful as contexts are shown in-place, while previews involve more changes on the screen and lead to more eye movements.

**Comment by eugen0329** [comment]
There are also several changes in modes. Regexp and case modes can be cycled with double ctrl-r and ctrl-s, smartcase mode is also supported along with `ignore` and `sensitive`, word replaced with textobj mode and now can be cycled using double ctrl-t (`none` to avoid restrictions, `word` to search only whole words and `line` for whole lines (the last is only supported by greps)). Menu has a couple of convenience improvements as well. Please, don't hesitate if you have any proposals on it, including UX (colors, positioning, keys), default keys, intuitiveness etc.

**Comment by ipod825** [comment]
Is it already supported to pass additional arguments to searcher? If not, I think you can add an additional option in the menu for passing arbitrary argument.

Also, I find the `<cr>` mapping very conuter-intuitive in the menu. I think `<cr>` should do what currently `<esc>` does.

Also, what does `path` in the menu do?

**Comment by ipod825** [comment]
A good use case for passing arbitrary arguments to the searcher is to search the within specific filetypes. For e.g., in ag, you need `-G ".cc"` to search only cpp files.

**Comment by eugen0329** [comment]
It's already on the roadmap, but I wanted to finish up with configurations/help files first and finally merge into master.

But it's already can be done using generic mechanism with specifying paths (was implemented as only a handful of utils support filetype filter options). Type `<c-o><c-p>` to input them. It recognizes globstar and extended globbing, so your desired behavior can be achieved using `**/*.cc **/*.h` syntax. Also make sure that extglob and globstar options are available and enabled (otherwise, overwrite your `&shell` to use bash with those options specified explicitly).

**Pull request merged**
