### PR TITLE
Add rg adapter

### PR DESCRIPTION
**Pull request by munyari**
Issue #9

Couldn't get the tests to run. After `bundle`, `bundle exec rake test` throws a bunch of errors that look like

```
       Failure/Error: vim = Vimrunner.start_gvim

       Vimrunner::NoSuitableVimError:
         No suitable Vim executable could be found for this system.
       Shared Example Group: "a backend" called from ./spec/plugin/backend/system_spec.rb:9
```

Note that I made `rg` the first option in opts.vim. This is up to your discretion whether you want it to be there.

### CODE REVIEW

**Comment by eugen0329** [comment]
It looks like you don't have appropriate vim with `+clientserver` support  to be runned with Vimrunner.

See https://github.com/AndrewRadev/vimrunner/blob/master/lib/vimrunner/platform.rb#L51.

**Comment by eugen0329** [comment]
Regarding your PR: everything looks great and I'll be glad to merge it. But there is one thing: `ag` seems to be more stable and mature project at the moment (while the first release of `rg` was only a month ago) and probably we should set it automatically with higher priority even despite `rg` speed. What do you think?

**Comment by munyari** [comment]
I agree with you there :smile: I'll put it at the bottom since it's still so new

**Comment by munyari** [comment]
Looks like you're right about vim, the `--remote` option does not work. Hmm...

**Comment by eugen0329** [comment]
> Probably better to wait until it's 1.0 and/or available in most package repositories

At first I thought the same:) However ag still has only minor version `0.33.0` while it's almost 4 years from the first release. But I agree that it's better to wait until it becomes available at least in apt repository.

**Comment by munyari** [comment]
Getting back to this, what do you think would be a good ordering? I'm thinking
1. ag
2. pt
3. rg
4. ack
5. git
6. grep

**Comment by eugen0329** [comment]
@munyari  Looks great!

**Comment by munyari** [comment]
ready for your review

**Comment by eugen0329** [comment]
Good job, thanks:)

**Pull request merged**
