### PR TITLE
Implement extended preview api

### PR DESCRIPTION
**Pull request by eugen0329**
Continues #104 

EXPERIMENTAL methods for opening previews:
```vim
" Specify the geometry
call esearch#out#win#map('e', { es -> es.preview({'width': 100, 'height': 15}) }) " absolute
call esearch#out#win#map('e', { es -> es.preview({'width': 0.5, 'height': 0.3}) }) " using %
" A wrapper around open() to achieve non-floating preview windows that
" can be focused and used for further editing. Accepts the same arguments 
" as open() to allow customization, except that the first  argument
" is `'vnew'` by default.
call esearch#out#win#map('e', { es -> es.split_preview() })
" Allow to check whether the preview is opened. Use case example:
" Toggle the preview instead of default zooming.
call esearch#out#win#map('p', { es ->
      \ es.is_preview_open() ? es.preview_close() : es.preview() })
" Specify alignment
call esearch#out#win#map('p', { es -> es.preview({'align': 'cursor'}) })
call esearch#out#win#map('p', { es -> es.preview({'align': 'top'}) })
call esearch#out#win#map('p', { es -> es.preview({'align': 'left'}) })
call esearch#out#win#map('p', { es -> es.preview({'align': 'bottom'}) })
call esearch#out#win#map('p', { es -> es.preview({'align': 'right'}) })
```

General API changes
```vim
echo b:esearch.unescaped_filename()
" b:esearch variable is passed as an argument
call esearch#out#win#map('e', { es -> es.open('split') })
" Allow multiple methods chaining using &&
call esearch#out#win#map('e', { es -> es.open('split') && execute('redraw') })
" Allow to specify variables to assign in an opened window without resetting them back
call b:open.apply('vnew', { 'let!': { '&l:foldlevel': 1000 } })
" Allow resolving filetypes under the cursor.
" Fast strategy use O(1) check for the file extension or tries to obtain it from an opened buffer.
" Complete strategy tries fast approach first, then use O(n) over all the defined filetypes
" Returns cached where possible
echo b:esearch.filetype({'fast': 1})
" Debounce name is changed to have lodash compliance
let b:preview = esearch#debounce(b:esearch.preview, 400)
call b:preview.apply({args})
" esearch#out#win#hook is defined to prevent autocommands bloat on the window reload:
" Will automatically wrap into augroup and remove the autocommand on reload
au User esearch_win_event
      \   let b:preview = esearch#debounce(b:esearch.preview, 400)
      \ | au CursorMoved <buffer> call b:preview.apply()
" Manually clean all user-defined hooks for the current buffer
au! esearch_win_event * <buffer>
```

Bugfix:
- fix corrupting undo on split_preview
- fix swaps handling
- fix showing redundant window lines if a buffer size is smallar than `'height'`
- fix dependency on CmdlineEnter event
- fix specifying height with a value less than `'&winminheight'`
- fix opening previews for files with special characters in path
- fix highlighting for files with special characters in paths

### CODE REVIEW

**Comment by eugen0329** [comment]
@ipod825

Please, try the following for previews using split:
```vim
au User esearch#out#win#init_post
      \  let b:open = esearch#debounce#trailing(b:esearch.open, 500)
      \| au CursorMoved <buffer> call b:open.invoke('vnew', {
      \   'stay': 1,
      \   'once': 1,
      \   'let!': { '&l:foldlevel': 1000 }
      \ })
```

**Comment by eugen0329** [comment]
It works for me when `set foldlevel=0 foldmethod=syntax` are globally specified. Windows opened previously keep the same value of foldlevel, but if the same file is opened again, new window inherits the value set during previewing, so yes, turns out that it works pretty similar to buffer local vars while being window-local.

**Comment by eugen0329** [comment]
Floating previews should work fine now.

**Comment by ipod825** [comment]
Yes. Preview (floating) works. It's just that fold setting that is annoying.

Not sure what that `once` means. But I don't like it's behavior. When I press `<Cr>`, it opens the file in the search window while the preview window is still open. I still prefer my own solution:
```vim
esearch#out#win#map('<cr>', {-> b:esearch.open('NewTabdrop')})
```
where `NewTabdrop` is the command defined by my [plugin](https://github.com/ipod825/vim-tabdrop).

**Comment by eugen0329** [comment]
Once feature is for maintaining reusable windows. It should open a window once and use it further without creating N windows on N opens. I'm still hesitate to rename the option to `'reuse': 1` as some plugins including ctrlp has a different meaning for it, but it'll likely to be called `'reuse'` later.

**Comment by eugen0329** [comment]
Proposal for `'reuse'`:
- Allow only values from `['single', 'per_opener', v:false]` 
- Set  `'single'` as a default as it's probably the most common use-case.

About your own opener: that's exactly why custom commands or callable openers are allowed :) The only question now is how to make the builtin reuse behavior convenient for the average user.

**Comment by ipod825** [comment]
> For preview windows foldlevel is set to 1000 (but is there some kind of an infinity value specified using set foldmethod=-1?) and reset to the original value when the preview is closed.

That should solve the problem. Preview window looks nice!

>once feature is for maintaining reusable windows. It should open a window once and use it further without creating N windows on N opens. And it manages preview windows per opener string. Not sure if it's the best option, so suggestions are welcome. Probably, we can allow users to specify 'reuse': 'per_opener' and 'reuse': 'single'. The purpose was to be able to conveniently define window layouts like this:

I don't really follow the idea and I have less interest in this feature. So maybe I'll try it when the api is stable.

**Comment by eugen0329** [comment]
There's another idea how to handle folds in split previews. I can add an option to locate cursor within a buffer and unfold the text under the cursor:
```
au User esearch#out#win#init_post
      \  let b:open = esearch#debounce#trailing(b:esearch.open, 500)
      \| au CursorMoved <buffer> call b:open.invoke('vnew', {
      \   'stay': 1,
      \   'once': 1,
      \   'locator': {line, col-> cursor(line, col) == 0 && execute('norm! zR') }
      \ })
```

Or alternatively to embed it as another option `'unfold': 1`.

**Comment by ipod825** [comment]
> There's another idea how to handle folds in split previews. I can add an option to locate cursor within a buffer and unfold the text under the cursor:

I am fine with any solution. The underlying problem seems just unsolvable unless vim fixes this problem. So users must pay the price of extra care if they want to have consistent behavior for fold. 
`vsplit` has advantage against floating window as it shows more context, though.

**Comment by ipod825** [comment]
Oh, I found that maybe `foldenable` is really local to window. Which might solve the problem.

**Comment by ipod825** [comment]
Indeed, setting `foldenable` works for my plugin.

**Comment by eugen0329** [comment]
There is another approach with `norm! zv` that just unfolds the required location per window and doesn't modify foldlevel. After superficial tests it turns to work as we expect.

> Oh, I found that maybe foldenable is really local to window. Which might solve the problem.

Than you can try `'let!'` option.

**Comment by ipod825** [comment]
>Than you can try 'let!' option.

Can you just try to `setlocal nofoldenable` in the preview split? This will require user to do no extra setting.

**Comment by eugen0329** [comment]
> vsplit has advantage against floating window as it shows more context, though.

I'd inspect capabilities to make docked floating windows that would behave like a split preview while leveraging all the benefits of floats. Do you know if it's possible to do using default configurations?

>Can you just try to setlocal nofoldenable in the preview split?

I've tried and it works, but I'm not sure if it's a good thing to be the default for opener. It'd probably be better to have a wrapper around open function like `es.split_preview()` in addition to `es.preview()` to set all the needed configs inside and to not mix the concerns.

**Comment by ipod825** [comment]
> I'd inspect capabilities to make docked floating windows that would behave like a split preview while leveraging all the benefits of floats. Do you know if it's possible to do using default configurations?

I don't understand the question. I am actually not familiar with the floating window api.

 > I've tried and it works, but I'm not sure if it's a good thing to be the default for opener. It'd probably be better to have a wrapper around open function like es.split_preview() in addition to es.preview() to set all the needed configs inside and to not mix the concerns.

My personal opinion is that `nofoldenable` is very important for preview and hence should be the default. I am not sure if you are talking about internal implementation or user customization hooks. But I prefer internally esearch set nofoldenable in the preview window without bothering the user to set it explicitly.

**Comment by eugen0329** [comment]
Another problem is swapfile. Until it doesn't exist everything is ok, but if you stumble across them, vim starts to constantly jump between the buffers (which also seems to be a case without swaps) and open the swap prompt. If the wait time is small you'll just stuck in trying to cancel the prompt as it will constantly reappear again.

**Comment by ipod825** [comment]
> Another problem is swapfile. Until it doesn't exist everything is ok, but if you stumble across

I've encountered exact the same problem and solved it with this [line](https://github.com/ipod825/vim-netranger/blob/9c82ce3b50aa885204ccb393e1711f0743ae42fc/pythonx/netranger/netranger.py#L879).

**Comment by eugen0329** [comment]
> I don't understand the question.

Docked means that it occupies all the width or all the height (depending on a config) and aligned to the right/bottom/etc.. Here is what floating window docked to the bottom look like: https://asciinema.org/a/232057

>  I am actually not familiar with the floating window api

Hmm, then maybe I misunderstood you, as I thought you've implemented the preview using exactly them.

> My personal opinion is that nofoldenable is very important for preview and hence should be the default

And it will be, but within `es.split_preview()` instead, since there are some other things to handle, such as preventing redundant jumps which could cause a situation near to deadlock  when a swap exists and debounce timeout is small enough, that I mentioned above.

**Comment by ipod825** [comment]
> Docked means that it occupies all the width or all the height (depending on a config) and aligned

I think you can find a reference implementation in [ncm2/float-preview.nvim](https://github.com/ncm2/float-preview.nvim).

> Hmm, then maybe I misunderstood you, as I thought you've implemented the preview using exactly them.

Yes. I only use split window. As floating window doesn't really make sense in my case.

> And it will be, but within es.split_preview() instead, since there are some other things to handle, such as preventing redundant jumps which could cause a situation near to deadlock when a swap exists and debounce timeout is small enough, that I mentioned above.

I've mentioned a solution to the swap message above. You can check if it works for you.

**Comment by eugen0329** [comment]
Replying to https://github.com/eugen0329/vim-esearch/pull/104#issuecomment-602260311:

The issue was ridiculously strange. `reltime()` was used to identify windows that don't have ids in legacy version, but for some peculiar reason this approach has a side effect: it (1) generates undo block (2) which is local to buffer (3) when assigning a variable (4) which is local to window (5) while trying to just fetch a time value. It's the most unexpected thing I've seen so far.

> I've mentioned a solution to the swap message above. You can check if it works for you.

It's a brilliant idea that I'm going to use within the floating preview implementation, but it's dangerous to use in split preview as they are designed to be switched to, so it's better to ask user first.

Open functionality for split previewing is wrapped into `es.split_preview()`. It handles unfolding per entire buffer and prevents redundant jumps to buffer which saves from reappearing swap prompt.

**Comment by eugen0329** [comment]
@ipod825 Here's an interesting solution to mitigate your problem with floating previews  size:
```vim
call esearch#out#win#map('p', { es ->
      \ es.is_preview_open() ? es.preview({'height': 30}) : es.preview() })
```
It expands the preview on double tap. As an alternative, split preview can also be configured to open on double `p` press.

**Comment by ipod825** [comment]
> The issue was ridiculously strange. reltime() was used to identify windows that don't have ids in legacy version, but for some peculiar reason this approach has a side effect: it (1) generates undo block (2) which is local to buffer (3) when assigning a variable (4) which is local to window (5) while trying to just fetch a time value. It's the most unexpected thing I've seen so far.

Very interesting. I also encountered the problem that vim's `job__start` does't not call back with the job id, (which neovim does!). Luckily, I was not aware of the function `reltime` and and just go directly with python's `time` module lol. 

> It's a brilliant idea that I'm going to use within the floating preview implementation, but it's dangerous to use in split preview as they are designed to be switched to, so it's better to ask user first.

You are right. I should probably also warn the user. Could you point out in the code how you implement this warning/asking? 

> Open functionality for split previewing is wrapped into es.split_preview(). It handles unfolding per entire buffer and prevents redundant jumps to buffer which saves from reappearing swap prompt.

Can you give an example? I tried the following snippet but got the appending error.
```vim
    au User esearch#out#win#init_post
          \ | let b:preview = esearch#debounce#trailing(b:esearch.split_preview, 100)
          \ | au CursorMoved <buffer> call b:preview.invoke()
```
```
Error detected while processing User Autocommands for "esearch#out#win#init_post":                                       
E716: Key not present in Dictionary: split_preview, 100) | au CursorMoved <buffer> call b:preview.invoke()               
E116: Invalid arguments for function esearch#debounce#trailing                                                           
E15: Invalid expression: esearch#debounce#trailing(b:esearch.split_preview, 100) | au CursorMoved <buffer> call b:preview
.invoke() 
```

**Comment by eugen0329** [comment]
> Can you give an example? I tried the following snippet but got the appending error

I think the first escaped bar is redundant. This should work:
```vim
au User esearch#out#win#init_post
      \   let b:preview = esearch#debounce#trailing(b:esearch.split_preview, 100)
      \ | au CursorMoved <buffer> call b:preview.invoke()
```

**Comment by eugen0329** [comment]
>Could you point out in the code how you implement this warning/asking?

The following lines should do the trick.
https://github.com/eugen0329/vim-esearch/blob/590c086274fc3d5106078ea4e00d3b50ff44ffb4/autoload/esearch/out/win/open.vim#L36-L40

The default prompt is used here, so our job here is just to not interfere. Minor note: interrupt probably can be throwed not only by pressing (A)bort within the swap prompt, but nevertheless the idea remains the same.

**Comment by ipod825** [comment]
> This should work:

The problem is that I used `development` branch. I switched to `implement-extended-preview-api` now.

**Comment by eugen0329** [comment]
@ipod825 There are some changes:
- You can specify the alignment like `{'align': 'right'}`.
- To improve the UX, this kind of previews is also enterable now. Multiple `p` press is for zooming, `P` is for entering.
- There's a User autocommand `esearch_win_event` to define hooks that will be wrapped in `esearch_win_event` and will automatically be garbage collected to prevent dozens of CursorMoved on reloading.
- Other autocommands are also without `#` in names, as it turned out, it has a side effect while using with `exists()` (rip consistent naming).
- Debouncing is now used with `esearch#debounce` and `.apply()` for brevity and to not reinvent the interface and be compliant with an existing library (lodash).

Please, let me know if you notice any bugs or you have any suggestions.

**Comment by ipod825** [comment]
> " close_on overrides default CursorMoved event.
au User esearch_win_event
      \   let b:preview = esearch#debounce(b:esearch.preview, 100)
      \ | au CursorMoved <buffer> call b:preview.apply({'align': 'right', 'close_on': []})

It is very nice!
However, I think there's some potential bug for the CursorMoved autocmd. Specifically, it doesn't work well with my [vim-netranger](https://github.com/ipod825/vim-netranger) plugin, which also registers CursorMoved autocmd.

To reproduce, use the vim snippet:
```vim
let vim_plug_file=expand(g:vim_dir . 'autoload/plug.vim')
if !filereadable(vim_plug_file)
    echo "Installing vim-plug.."
    echo ""
    execute 'silent !mkdir -p ' . g:vim_dir . 'autoload'
    " call system('wget https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim -P ' . g:vim_dir . 'autoload')
    call system('curl -fLo '.g:vim_dir.'autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim')
endif

call plug#begin(g:vim_dir . 'bundle')

Plug 'ipod825/vim-netranger'
Plug 'eugen0329/vim-esearch', {'branch': 'development'}
call plug#end()

au User esearch_win_event
\   let b:preview = esearch#debounce(b:esearch.preview, 100)
\ | au CursorMoved <buffer> call b:preview.apply({'align': 'right', 'close_on': []})
```
Have the following directory layout:
~/test
  |  test.cpp
With some content in test.cpp.
Then open the `test` directory with `vim ~/test` (ensure it's vim-netranger but not other file explorer plugin that is opening the directory). A preview panel should appear on the right showing the content of test.cpp. Then use esaerch to search a keyword in test.cpp, making sure the preview floating window appears. Go back to the tabpage of the directory. Press `k` then `j`. Then vim crashes with segmentation fault.

I've checked the problem on my side. If I modify these lines:
https://github.com/ipod825/vim-netranger/blob/f472acdba36c89f045b0c10ba7cd59cfcb95bc93/pythonx/netranger/netranger.py#L877-L884
into
```python 
with self.ManualRefreshOnWidthChange():
    Vim.command(f'silent botright vsplit {cur_node.fullpath}')
```
vim doesn't crash with the aforementioned procedure. However, by adding back another line
```python
with self.ManualRefreshOnWidthChange():
    Vim.command(f'silent botright vsplit {cur_node.fullpath}')
    Vim.command('wincmd l')
```
vim will crash.

**Comment by eugen0329** [comment]
Not sure whether it's related to the way the floating windows are handled here of to neovim internals, but the problem seems to be related to a missing closing on leaving or creating a tab. Similar problem was spotted in autotests when using `%bwipeout` command. Sometimes it cleans up everything properly, but sometimes it silently crashes with unknown errors and presumably it's segfault as well. Please, pull development and check if it still occurs.

**Comment by ipod825** [comment]
Solved. Thanks!

**Comment by eugen0329** [comment]
BTW another swapfiles quirk when using `shormess`: if it's used, then all further opens will be considered as if `edit` was confirmed manually (unless the buffer wasn't wiped out after previewing), so if you still rely on it in your implementation, then you'll probably should inspect the case to prevent users from potential changes loss.

**Comment by ipod825** [comment]
I see. So is there still a split window option for preview? How did you takle the swapfile issue now?

**Comment by eugen0329** [comment]
As always, vim doesn't expose methods to interface swaps and the default flow and handling them, so the option is to follow the docs and to implement handling with commands that are available. Logic is intentionally putted in a single place to keep every detail in mind:
https://github.com/eugen0329/vim-esearch/blob/aad063209b2c426cb8473454e0627cb16423878a/autoload/esearch/preview.vim#L246-L272

Builtin behavior is:
- If the buffer is displayed in at least one window - don't ask about swaps
- If the buffer is not displayed and has a swap created by another process (swapinfo() doesn't work) - it's better to open it with readonly flag using `:view` to not miss the swap prompt on further opens.

Swapname and swapinfo return swap data for the current process only. The only way to obtain the information is using opening with further cancelling the swap prompt using `v:swapchoice` var. https://github.com/eugen0329/vim-esearch/blob/aad063209b2c426cb8473454e0627cb16423878a/autoload/esearch/preview.vim#L274-L286

Sound complicated, but it's the default behavior which was supposed to be exposed as a set of functions, but unfortunately it's not. There are actually even more sideffects than I (and probably you too) didn't expect like corrupting the undo on `:edit`, accidental triggering `confirm save` prompt for modified buffers and others that are already taken into account here, therefore I'm not sure that it can be done easier without using pseudo buffers, which is slower when opening on CursorMoved and less convenient as we don't have recent changes in regular buffers.

There's a recover.vim plugin that also handles swaps and does the similar with swapexists, but as it needs far more information about swaps - logic there is even more sophisticated than checking for opened windows and existing files, therefore swap turns out to always be a challenge.

Anyway, preview feature is nicely covered with ~48 integration test cases, so it can be considered pretty stable. Regarding the SIGFAULT problem: it's already mentioned in one of nvim repo PRs. No reason to push them more.

**Comment by ipod825** [comment]
New issue: the search buffer clears visual selection (for e.g. `ve`) if the CursorMoved event is registered. I guess this can be fixed by checking the vim mode in the preview function (if visual mode, do nothing).

**Comment by eugen0329** [comment]
Disabled for visual. Probably, it can be restored with gv after leaving the floating win, but simply adding `norm! gv` isn't working and updating during visual seems to not be a vital feature, so I'd like to not bloat the code for now. Please, check if it's working in dev branch.

**Comment by ipod825** [comment]
It works. Thanks!

**Pull request merged**
